/**
 * PEHRA Mock Data Store
 * Provides initial data for development and offline demo safety
 */

export const INITIAL_EXAMS = [
  {
    id: "exam-001",
    title: "Semester End Examination — Mathematics",
    subject: "Mathematics (MATH-401)",
    date: "2026-08-18",
    time: "10:00 AM – 01:00 PM",
    startTime: "10:00",
    endTime: "13:00",
    hall: "Hall A",
    hallId: "hall-a",
    students: 72,
    totalSeats: 72,
    invigilator: "Prof. Nandini Rawat",
    status: "live",
    currentStep: 6,
    progress: 100,
    elapsed: "01:24:32",
    instructions: "Strict offline environment. No smart devices or unauthorized papers permitted.",
    evidenceRetention: false,
    seatingConfig: {
      rows: 8,
      columns: 9,
      aisles: [4],
      disabledSeats: [],
    },
    cameras: [
      { id: "cam-01", name: "Front Overhead Cam 01", type: "edge_ai", zone: "Zone A (Front)", status: "connected", fps: 30 },
      { id: "cam-02", name: "Center Overhead Cam 02", type: "edge_ai", zone: "Zone B (Center)", status: "connected", fps: 30 },
      { id: "cam-03", name: "Rear Overhead Cam 03", type: "rtsp", zone: "Zone C (Rear)", status: "connected", fps: 28 },
    ],
    calibration: {
      coverageScore: 100,
      blindSpotsCount: 0,
      zonesMapped: 3,
      status: "verified",
    },
  },
  {
    id: "exam-002",
    title: "Digital Electronics — Internal Assessment",
    subject: "Digital Electronics (ECE-202)",
    date: "2026-08-19",
    time: "09:00 AM – 11:00 AM",
    startTime: "09:00",
    endTime: "11:00",
    hall: "Hall B",
    hallId: "hall-b",
    students: 60,
    totalSeats: 60,
    invigilator: "Dr. R. Sharma",
    status: "upcoming",
    currentStep: 6,
    progress: 100,
    instructions: "Calculators allowed (Non-programmable only).",
    evidenceRetention: false,
    seatingConfig: {
      rows: 6,
      columns: 10,
      aisles: [5],
      disabledSeats: [],
    },
    cameras: [
      { id: "cam-01", name: "Primary Lab Cam", type: "edge_ai", zone: "Lab Front", status: "connected", fps: 30 },
      { id: "cam-02", name: "Secondary Lab Cam", type: "webcam", zone: "Lab Rear", status: "connected", fps: 30 },
    ],
    calibration: {
      coverageScore: 100,
      blindSpotsCount: 0,
      zonesMapped: 2,
      status: "verified",
    },
  },
  {
    id: "exam-003",
    title: "Database Systems — Mid Semester",
    subject: "Database Systems (CS-303)",
    date: "2026-08-15",
    time: "02:00 PM – 04:00 PM",
    startTime: "14:00",
    endTime: "16:00",
    hall: "Hall C",
    hallId: "hall-c",
    students: 70,
    totalSeats: 70,
    invigilator: "Prof. V. Gupta",
    status: "completed",
    currentStep: 6,
    progress: 100,
    instructions: "Closed book exam. Rough sheet provided by hall supervisor.",
    evidenceRetention: false,
    summary: {
      attendanceCount: 68,
      absentCount: 2,
      totalEvents: 17,
      reviewedCount: 8,
      falseAlarmsCount: 5,
      confirmedIncidentsCount: 3,
      avgConfidence: 94.2,
      riskDistribution: {
        normal: 61,
        underReview: 4,
        highRisk: 3,
      },
      auditLog: [
        {
          id: "evt-101",
          time: "02:24 PM",
          seatId: "C-04",
          eventType: "Repeated Head Turn",
          severity: "medium",
          confidence: "91%",
          invigilatorAction: "False Alarm",
          notes: "Student was checking the wall clock.",
        },
        {
          id: "evt-102",
          time: "02:45 PM",
          seatId: "B-08",
          eventType: "Body Orientation Shift",
          severity: "high",
          confidence: "88%",
          invigilatorAction: "Confirmed Incident",
          notes: "Invigilator approached desk; notes sheet confiscated.",
        },
        {
          id: "evt-103",
          time: "03:12 PM",
          seatId: "A-02",
          eventType: "Hand Movement Anomaly",
          severity: "low",
          confidence: "79%",
          invigilatorAction: "False Alarm",
          notes: "Dropping and picking up pencil.",
        },
        {
          id: "evt-104",
          time: "03:38 PM",
          seatId: "D-06",
          eventType: "Neighbor Interaction Pattern",
          severity: "high",
          confidence: "93%",
          invigilatorAction: "Confirmed Incident",
          notes: "Repeated synchronized head turns towards Seat D-07.",
        },
      ],
      privacyAttestation: {
        zeroBiometricStored: true,
        edgeInferenceVerified: true,
        noCloudVideoSent: true,
        dataMinimizationCompliant: true,
        auditTimestamp: "2026-08-15T16:05:00Z",
      },
    },
  },
  {
    id: "exam-004",
    title: "Computer Networks — Internal Assessment",
    subject: "Computer Networks (CS-304)",
    date: "2026-08-14",
    time: "11:00 AM – 01:00 PM",
    startTime: "11:00",
    endTime: "13:00",
    hall: "Hall B",
    hallId: "hall-b",
    students: 64,
    totalSeats: 64,
    invigilator: "Prof. K. Verma",
    status: "completed",
    currentStep: 6,
    progress: 100,
    instructions: "Standard internal test protocol.",
    summary: {
      attendanceCount: 63,
      absentCount: 1,
      totalEvents: 12,
      reviewedCount: 6,
      falseAlarmsCount: 4,
      confirmedIncidentsCount: 2,
      avgConfidence: 91.5,
      riskDistribution: {
        normal: 58,
        underReview: 3,
        highRisk: 2,
      },
      auditLog: [
        {
          id: "evt-201",
          time: "11:34 AM",
          seatId: "B-03",
          eventType: "Prolonged Unusual Movement",
          severity: "medium",
          confidence: "87%",
          invigilatorAction: "False Alarm",
          notes: "Student stretching neck.",
        },
        {
          id: "evt-202",
          time: "12:15 PM",
          seatId: "C-09",
          eventType: "Neighbor Interaction Pattern",
          severity: "high",
          confidence: "94%",
          invigilatorAction: "Confirmed Incident",
          notes: "Whispering pattern detected.",
        },
      ],
      privacyAttestation: {
        zeroBiometricStored: true,
        edgeInferenceVerified: true,
        noCloudVideoSent: true,
        dataMinimizationCompliant: true,
        auditTimestamp: "2026-08-14T13:02:15Z",
      },
    },
  },
  {
    id: "exam-005",
    title: "Operating Systems — Semester Examination",
    subject: "Operating Systems (CS-301)",
    date: "2026-08-20",
    time: "10:00 AM – 01:00 PM",
    startTime: "10:00",
    endTime: "13:00",
    hall: "Hall A",
    hallId: "hall-a",
    students: 72,
    totalSeats: 72,
    invigilator: "Prof. Nandini Rawat",
    status: "draft",
    currentStep: 3,
    progress: 50,
    instructions: "Comprehensive 3-hour theoretical exam.",
    evidenceRetention: false,
    seatingConfig: {
      rows: 8,
      columns: 9,
      aisles: [4],
      disabledSeats: [],
    },
    cameras: [],
    calibration: {
      coverageScore: 0,
      blindSpotsCount: 72,
      zonesMapped: 0,
      status: "pending",
    },
  },
];
